thingsboard/tbmq

- application/src/main/resources/thingsboard-mqtt-broker.yml
> [1.0.2] Fix CORS configuration issue introduced in Spring 5.3

- application/src/main/java/org/thingsboard/mqtt/broker/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/ClientActorContext.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/ClientActorConfiguration.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/handlers/MqttSubscribeHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/subscription/ClientSubscriptionService.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/subscription/ClientSubscriptionServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/device/DeviceActorConfiguration.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/device/PersistedDeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/ApplicationPersistenceProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/ApplicationPackProcessingCtx.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/PersistedPublishMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/DeviceActorManagerImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/processing/MsgDispatcherServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/processing/downlink/DownLinkProxyImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/stats/StatsManagerImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/ClientSubscriptionCache.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/TopicSubscription.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionCacheService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/TopicSharedSubscription.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/subscription/ClientSubscriptionServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/SharedSubscriptionsIntegrationTestCase.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/persistentsession/AppSharedSubscriptionsIntegrationTestCase.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/ApplicationPersistedMsgCtxServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/processing/MsgDispatcherServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionCacheServiceImplTest.java
- application/src/test/resources/logback.xml
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ClientSessionInfo.java
> [1.1.1] Bug/shared subscriptions qos 0

- application/src/main/java/org/thingsboard/mqtt/broker/controller/BaseController.java
- application/src/main/java/org/thingsboard/mqtt/broker/controller/ClientSessionController.java
- application/src/main/java/org/thingsboard/mqtt/broker/dto/ShortClientSessionInfoDto.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfos.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/util/ClientSessionInfoFactory.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImplTest.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ClientSessionQuery.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/page/PageLink.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/page/TimePageLink.java
> [1.1.1] Client session advanced filtering

- ui-ngx/src/app/modules/home/pages/profile/change-password-dialog.component.html
On the Profile page when a user changes the password and hits the "Skip" button - the user is logged out.
> [1.1.1] Fix: hide Skip button in Profile - Change password 

- application/src/main/java/org/thingsboard/mqtt/broker/controller/BaseController.java
- application/src/main/java/org/thingsboard/mqtt/broker/controller/SubscriptionController.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/Subscription.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionDto.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionPaginationService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionPaginationServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionQuery.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptions.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/subscription/shared/SharedSubscriptionPaginationServiceImplTest.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ClientSessionState.java
> [1.1.1] Shared subscriptions management

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/disconnect/DisconnectServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/util/MqttReasonCode.java
- application/src/main/java/org/thingsboard/mqtt/broker/util/MqttReasonCodeResolver.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
- application/src/test/java/org/thingsboard/mqtt/broker/AbstractPubSubIntegrationTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/disconnect/DisconnectServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/SessionsLimitIntegrationTestCase.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImplTest.java
> [1.2.1] Feature/sessions limit

- application/src/main/java/org/thingsboard/mqtt/broker/server/AbstractMqttHandlerProvider.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/tls/MqttSslChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/wss/MqttWssChannelInitializer.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
> [1.2.2] Cipher suites control

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/ClientActor.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/cluster/ClearSessionMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/cluster/ConnectionRequestMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/mqtt/MqttPublishMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/mqtt/QueueableMqttMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/MqttMessageHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/state/QueuedMqttMessages.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/device/messages/DeviceDisconnectedEventMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/adaptor/ProtoConverter.java
- application/src/main/java/org/thingsboard/mqtt/broker/session/ClientMqttActorManagerImpl.java
- pom.xml
> [1.2.2] Fix for direct memory leak

- ui-ngx/src/app/core/http/retained-msg.service.ts
> [1.2.2] Fix: encode topic name in deleteRetainedMessage method

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/ActorProcessor.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/ActorProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/config/IncomingRateLimitsConfiguration.java
- application/src/main/java/org/thingsboard/mqtt/broker/config/OutgoingRateLimitsConfiguration.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/MqttSessionHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/processing/downlink/basic/BasicDownLinkProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/security/model/SecurityUser.java
- application/src/main/java/org/thingsboard/mqtt/broker/session/ClientSessionCtx.java
- application/src/main/java/org/thingsboard/mqtt/broker/session/SessionContext.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/connect/ConnectServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/RateLimitsIntegrationTestCase.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/processing/downlink/basic/BasicDownLinkProcessorImplTest.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ApplicationSharedSubscription.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/BaseData.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/SearchTextBasedWithAdditionalInfo.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/dto/WebSocketConnectionDto.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/id/IdBased.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/ws/WebSocketConnectionServiceImplTest.java
* Enable flow control feature for MQTT 3.x clients.
* Added rate limits for non-persisting subscribers with QoS = 0
> [1.2.2] Backpressure improvements

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/handlers/MqttSubscribeHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/adaptor/NettyMqttConverter.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/retain/ConcurrentMapRetainMsgTrie.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/ConcurrentMapSubscriptionTrie.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/SubscriptionTrie.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/subscription/ValueWithTopicFilter.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/handlers/MqttSubscribeHandlerTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/retain/ConcurrentMapRetainMsgTrieTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/subscription/ConcurrentMapSubscriptionTrieTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/subscription/SubscriptionTrieSuiteTest.java
- common/util/src/main/java/org/thingsboard/mqtt/broker/common/util/BrokerConstants.java
- dao/src/main/java/org/thingsboard/mqtt/broker/dao/service/DefaultTopicValidationService.java
> [1.3.1] Fix subscription matching

- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/providers/BasicMqttClientAuthProvider.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/providers/SslMqttClientAuthProvider.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/AbstractRateLimitCacheService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitCaffeineCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitRedisCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/DevicePersistenceProcessorImpl.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
- application/src/test/java/org/thingsboard/mqtt/broker/cache/CaffeineCacheDefaultConfigurationTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/persistentsession/DevicePersistedMessagesIntegrationTestCase.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitCaffeineCacheServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitRedisCacheServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/device/DevicePersistenceProcessorImplTest.java
- common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/CacheConstants.java
- common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/CacheNameResolver.java
- common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TBRedisCacheConfiguration.java
- common/cache/src/main/java/org/thingsboard/mqtt/broker/cache/TbCaffeineCacheConfiguration.java
- dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/MqttClientCredentialsServiceImpl.java
- dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/device/DevicePacketIdAndSerialNumberServiceImpl.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/client/device/DevicePacketIdAndSerialNumberServiceTest.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/MqttClientCredentialsServiceTest.java
Added parameter to be able to append cache prefix for all cache keys.
> [1.3.1] Feature/cache prefix

- application/src/main/java/org/thingsboard/mqtt/broker/server/MqttHandlerCtx.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/MqttSessionHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitBatchProcessor.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitBatchProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitCaffeineCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitRedisCacheServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/MsgPersistenceManagerImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/processing/MsgDispatcherServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/processing/MultiplePublishMsgCallbackWrapper.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitBatchProcessorImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/limits/RateLimitServiceImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/MsgPersistenceManagerImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/processing/MsgDispatcherServiceImplTest.java
- common/util/src/main/java/org/thingsboard/mqtt/broker/common/util/ThingsBoardExecutors.java
Put your PR description here instead of this sentence.
> [1.3.1] Rate limits batch processing

- ui-ngx/src/app/core/http/stats.service.ts
- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/wizard/connection-wizard-dialog.component.ts
- ui-ngx/src/app/modules/home/pages/monitoring/monitoring.component.html
- ui-ngx/src/app/modules/home/pages/monitoring/monitoring.component.ts
- ui-ngx/src/app/shared/models/chart.model.ts
- ui-ngx/src/app/shared/models/ws-client.model.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added stats chart key processedBytes
> Added stats chart key processedBytes

- ui-ngx/src/app/core/http/mqtt-js-client.service.ts
Put your PR description here instead of this sentence.
> ws-client: on topic subscription added subscriptionIdentifier

- ui-ngx/src/app/modules/home/components/home-charts/home-charts.component.ts
- ui-ngx/src/app/shared/models/chart.model.ts
Put your PR description here instead of this sentence.
> home charts tooltip added bytes

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/ActorProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/DefaultEnhancedAuthenticationService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/EnhancedAuthenticationService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/enhanced/EnhancedAuthFailureReason.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/enhanced/EnhancedAuthResponse.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/enhanced/ScramAuthCallbackHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/auth/enhanced/ScramSaslServerWithCallback.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/ActorProcessorImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/controller/BaseMqttClientCredentialsControllerTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/auth/DefaultEnhancedAuthenticationServiceTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/auth/enhanced/ScramAuthCallbackHandlerTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/integration/Mqtt5AuthIntegrationTestCase.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/client/credentials/ScramMqttCredentials.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/AbstractServiceTest.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/MqttClientCredentialsServiceTest.java
Put your PR description here instead of this sentence.
> Tests for enhnanced auth & refactoring

- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/ClientActor.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/PubAckResponseMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/messages/PubRecResponseMsg.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/MqttMessageHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/MqttMessageHandlerImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/service/handlers/MqttPublishHandler.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/state/MqttMsgWrapper.java
- application/src/main/java/org/thingsboard/mqtt/broker/actors/client/state/OrderedProcessingQueueImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/GenericClientSessionCtxManagerImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/util/MqttReasonCodeResolver.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/service/handlers/MqttPublishHandlerTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/actors/client/state/OrderedProcessingQueueImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/GenericClientSessionCtxManagerImplTest.java
This PR contains performance improvements for the processing of MQTT Publish packets that are sent from the clients to the TBMQ. This includes better threads usage and application resource consumption. Two queues are replaced with a single one.
> MQTT publish ordered processing performance improvement

- application/src/main/java/org/thingsboard/mqtt/broker/controller/ClientSessionController.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImpl.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/client/session/ClientSessionPageInfosImplTest.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/ClientSessionQuery.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/client/session/SubscriptionOperation.java
- ui-ngx/src/app/modules/home/pages/sessions/session-filter-config.component.html
- ui-ngx/src/app/modules/home/pages/sessions/session-filter-config.component.ts
- ui-ngx/src/app/modules/home/pages/sessions/sessions-table-config.ts
- ui-ngx/src/app/shared/models/query/query.models.ts
- ui-ngx/src/app/shared/models/session.model.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
We have enhanced the client sessions filter by client IP address and operations with subscription count.
Before:
After:
> Improved client sessions filter

- application/src/main/java/org/thingsboard/mqtt/broker/controller/MqttClientCredentialsController.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/client/credentials/ClientCredentialsQuery.java
- dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/DefaultMqttClientCredentialsDao.java
- dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/MqttClientCredentialsRepository.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/MqttClientCredentialsServiceTest.java
- ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-filter-config.component.html
- ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-filter-config.component.ts
- ui-ngx/src/app/modules/home/pages/client-credentials/client-credentials-table-config.resolver.ts
- ui-ngx/src/app/shared/models/credentials.model.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
We have enhanced the MQTT client credentials filter by client ID, username, and certificate CN parameters.
Before:
After:
> Improved MQTT client credentials filter

- application/src/main/java/org/thingsboard/mqtt/broker/controller/RetainedMsgController.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/retain/RetainedMsgPageServiceImpl.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/retain/RetainedMsgPageServiceImplTest.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/mqtt/retained/RetainedMsgQuery.java
Implementation of advanced filtering for retained messages.
> Retained msg advanced filtering

- application/src/main/java/org/thingsboard/mqtt/broker/controller/SystemInfoController.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/http/TBMQReleaseService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/retain/RetainedMsgListenerServiceImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/provider/AbstractServiceProvider.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/ttl/TimeseriesCleanUpService.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/BrokerConstants.java
- common/data/src/main/java/org/thingsboard/mqtt/broker/common/data/util/BytesUtil.java
- ui-ngx/src/app/core/http/config.service.ts
- ui-ngx/src/app/modules/home/components/version-card/version-card.component.ts
- ui-ngx/src/app/shared/models/config.model.ts
I moved the latest version available check to the backend to work in a scheduled fashion to prevent GitHub rate limiting.
> TBMQ latest version available moved to backend

- msa/black-box-tests/pom.xml
- pom.xml
This PR contains Vulnerability fixes.
> Vulnerabilities fix

- dao/src/main/java/org/thingsboard/mqtt/broker/dao/client/MqttClientCredentialsServiceImpl.java
- dao/src/test/java/org/thingsboard/mqtt/broker/dao/service/MqttClientCredentialsServiceTest.java
> Allow edit system WS client credentials

- application/src/main/java/org/thingsboard/mqtt/broker/install/ThingsboardMqttBrokerInstallService.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/install/data/WebSocketClientSettings.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/install/update/DefaultDataUpdateService.java
> Fix WS client admin settings with missing parameter

- k8s/gcp/README.md
- k8s/gcp/database-setup.yml
- k8s/gcp/k8s-delete-all.sh
- k8s/gcp/k8s-delete-tbmq.sh
- k8s/gcp/k8s-deploy-tbmq.sh
- k8s/gcp/k8s-install-tbmq.sh
- k8s/gcp/k8s-upgrade-tbmq.sh
- k8s/gcp/kafka/default-values-kafka.yml
- k8s/gcp/kafka/values-kafka.yml
- k8s/gcp/receipts/http-load-balancer.yml
- k8s/gcp/receipts/https-load-balancer.yml
- k8s/gcp/receipts/mqtt-load-balancer.yml
- k8s/gcp/redis/default-values-redis.yml
- k8s/gcp/redis/values-redis.yml
- k8s/gcp/tb-broker-cache-configmap.yml
- k8s/gcp/tb-broker-configmap.yml
- k8s/gcp/tb-broker-db-configmap.yml
- k8s/gcp/tb-broker-namespace.yml
- k8s/gcp/tb-broker.yml
This PR introduces Kubernetes scripts for deploying a TBMQ cluster on Google Kubernetes Engine (GKE). The scripts are intended to serve as part of our official GCP installation guide and provide a ready-to-use setup tailored for GCP infrastructure.
> GCP GKE scripts 2.0.1

- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/ApplicationPersistenceProcessorImpl.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/delivery/AppMsgBufferedDeliveryStrategy.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/delivery/AppMsgDeliveryStrategy.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/delivery/AppMsgFlushedDeliveryStrategy.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/ApplicationMsgAcknowledgeStrategyFactory.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/ApplicationPackProcessingCtx.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/BurstSubmitStrategy.java
- application/src/main/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/processing/PersistedMsg.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/ApplicationPersistenceProcessorImplTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/delivery/AppMsgBufferedDeliveryStrategyTest.java
- application/src/test/java/org/thingsboard/mqtt/broker/service/mqtt/persistence/application/delivery/AppMsgFlushedDeliveryStrategyTest.java
This PR introduces a configurable strategy for delivering MQTT application messages in TBMQ. The goal is to provide flexibility between low-latency and high-throughput delivery modes by allowing users to choose between two delivery strategies: flushing each message immediately or buffering messages and flushing them in batches.
- Introduced `AppMsgDeliveryStrategy` interface to abstract application message delivery logic.
1. **`AppMsgFlushedDeliveryStrategy`**  
- Flushes the Netty channel **immediately after each message**.
- Prioritizes **low-latency** and real-time delivery.
- Enabled when `write-and-flush=true`.
2. **`AppMsgBufferedDeliveryStrategy`**  
- Buffers messages in Netty and **flushes after N messages**, based on the configured `buffered-msg-count`.
- Optimized for **higher …
> Strategies of message delivery for Application clients

- k8s/helm/aws/cluster.yml
- k8s/helm/aws/gp3-def-sc.yml
This pull request introduces two configuration files intended to streamline the deployment of TBMQ using Helm on AWS infrastructure (EKS):
1. cluster.yml - a sample EKS cluster definition file for eksctl with multiple managed node groups labeled by role: tbmq, tbmq-ie, kafka, redis, and postgresql.
2. gp3-def-sc.yml - storage class definition for Amazon EBS gp3, marked as the default.
These files will be referenced as part of the official TBMQ Helm-based installation documentation for EKS.
> Added cluster.yml and gp3-def-sc.yml for Helm-based TBMQ installation on EKS

- application/src/main/java/org/thingsboard/mqtt/broker/server/AbstractMqttChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/MqttChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/tcp/MqttTcpChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/tcp/MqttTcpServerContext.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/tls/MqttSslChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/tls/MqttSslServerContext.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/ws/MqttWsChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/ws/MqttWsServerContext.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/wss/MqttWssChannelInitializer.java
- application/src/main/java/org/thingsboard/mqtt/broker/server/wss/MqttWssServerContext.java
- application/src/main/resources/thingsboard-mqtt-broker.yml
This PR extends proxy protocol configuration to support both global and per-listener settings.
* Introduces **per-listener `proxy_enabled`** parameters (`MQTT_TCP_PROXY_PROTOCOL_ENABLED`, `MQTT_SSL_PROXY_PROTOCOL_ENABLED`, `MQTT_WS_PROXY_PROTOCOL_ENABLED`, `MQTT_WSS_PROXY_PROTOCOL_ENABLED`).
* Per-listener settings are **unset by default** and inherit the global `MQTT_PROXY_PROTOCOL_ENABLED` value.
* When explicitly set, a per-listener flag overrides the global setting.
* Maintains **backward compatibility**: existing global config continues to work without change.
* Updated configuration comments and documentation for clarity.
This allows finer control of proxy protocol usage while preserving simple global configuration for common cases.
**Example**
```
MQTT_PROXY_PROTOCOL_ENABLED=true …
```
> Enable/disable proxy protocol per MQTT listener
